package sop_corba;


/**
* sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* jueves 11 de junio de 2020 02:55:54 PM COT
*/

public interface GestionPacientesOperations 
{
  boolean registrarPaciente (sop_corba.GestionPacientesPackage.pacienteDTO objPaciente);
  sop_corba.GestionPacientesPackage.pacienteDTO consultarPaciente (int numeroHabitacion);
} // interface GestionPacientesOperations
