package sop_corba;


/**
* sop_corba/GestionAsintomaticosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomatico.idl
* jueves 11 de junio de 2020 05:23:26 PM COT
*/

public interface GestionAsintomaticosOperations 
{
  void registrarAsintomatico (sop_corba.GestionAsintomaticosPackage.asintomaticoDTO asin_reg, org.omg.CORBA.BooleanHolder res);
  boolean consultarAsintomatico (int id, sop_corba.GestionAsintomaticosPackage.asintomaticoDTOHolder asin_bus);
} // interface GestionAsintomaticosOperations
