package sop_corba;

/**
* sop_corba/GestionAsintomaticosHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomatico.idl
* jueves 11 de junio de 2020 05:23:26 PM COT
*/

public final class GestionAsintomaticosHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionAsintomaticos value = null;

  public GestionAsintomaticosHolder ()
  {
  }

  public GestionAsintomaticosHolder (sop_corba.GestionAsintomaticos initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionAsintomaticosHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionAsintomaticosHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionAsintomaticosHelper.type ();
  }

}
