package sop_corba;

/**
* sop_corba/GestionPacientesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomatico.idl
* jueves 11 de junio de 2020 04:36:57 PM COT
*/

public final class GestionPacientesHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionPacientes value = null;

  public GestionPacientesHolder ()
  {
  }

  public GestionPacientesHolder (sop_corba.GestionPacientes initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionPacientesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionPacientesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionPacientesHelper.type ();
  }

}
