package sop_corba;


/**
* sop_corba/GestionPacientes.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* jueves 11 de junio de 2020 02:55:54 PM COT
*/

public interface GestionPacientes extends GestionPacientesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionPacientes
