package sop_corba;


/**
* sop_corba/GestionAsintomaticos.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomatico.idl
* jueves 11 de junio de 2020 05:23:26 PM COT
*/

public interface GestionAsintomaticos extends GestionAsintomaticosOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionAsintomaticos
