package sop_corba.GestionPacientesPackage;


/**
* sop_corba/GestionPacientesPackage/asintomaticoDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomatico.idl
* jueves 11 de junio de 2020 04:36:57 PM COT
*/

public final class asintomaticoDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public String apellido = null;
  public String tipo_id = null;
  public int id = (int)0;
  public String direccion = null;

  public asintomaticoDTO ()
  {
  } // ctor

  public asintomaticoDTO (String _nombre, String _apellido, String _tipo_id, int _id, String _direccion)
  {
    nombre = _nombre;
    apellido = _apellido;
    tipo_id = _tipo_id;
    id = _id;
    direccion = _direccion;
  } // ctor

} // class asintomaticoDTO
