package sop_corba.GestionPacientesPackage;

/**
* sop_corba/GestionPacientesPackage/asintomaticoDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges-asintomatico.idl
* jueves 11 de junio de 2020 04:36:57 PM COT
*/

public final class asintomaticoDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.GestionPacientesPackage.asintomaticoDTO value = null;

  public asintomaticoDTOHolder ()
  {
  }

  public asintomaticoDTOHolder (sop_corba.GestionPacientesPackage.asintomaticoDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.GestionPacientesPackage.asintomaticoDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.GestionPacientesPackage.asintomaticoDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.GestionPacientesPackage.asintomaticoDTOHelper.type ();
  }

}
