package sop_corba.GestionPacientesPackage;


/**
* sop_corba/GestionPacientesPackage/pacienteDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from operaciones.idl
* jueves 11 de junio de 2020 02:55:54 PM COT
*/

public final class pacienteDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombre = null;
  public String apellido = null;
  public int edad = (int)0;
  public int numeroHabitacion = (int)0;

  public pacienteDTO ()
  {
  } // ctor

  public pacienteDTO (String _nombre, String _apellido, int _edad, int _numeroHabitacion)
  {
    nombre = _nombre;
    apellido = _apellido;
    edad = _edad;
    numeroHabitacion = _numeroHabitacion;
  } // ctor

} // class pacienteDTO
